/********************************************************************
* MyMainFrameDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MyMainFrameDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMyMainFrameDict();
extern void G__cpp_setup_inheritanceMyMainFrameDict();
extern void G__cpp_setup_typetableMyMainFrameDict();
extern void G__cpp_setup_memvarMyMainFrameDict();
extern void G__cpp_setup_globalMyMainFrameDict();
extern void G__cpp_setup_memfuncMyMainFrameDict();
extern void G__cpp_setup_funcMyMainFrameDict();
extern void G__set_cpp_environmentMyMainFrameDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MyMainFrame.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MyMainFrameDictLN_TString;
extern G__linked_taginfo G__MyMainFrameDictLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__MyMainFrameDictLN_string;
extern G__linked_taginfo G__MyMainFrameDictLN_basic_stringstreamlEcharcOchar_traitslEchargRcOallocatorlEchargRsPgR;
extern G__linked_taginfo G__MyMainFrameDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MyMainFrameDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MyMainFrameDictLN_TList;
extern G__linked_taginfo G__MyMainFrameDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MyMainFrameDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MyMainFrameDictLN_TQObjSender;
extern G__linked_taginfo G__MyMainFrameDictLN_TGWindow;
extern G__linked_taginfo G__MyMainFrameDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__MyMainFrameDictLN_TGTextButton;
extern G__linked_taginfo G__MyMainFrameDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__MyMainFrameDictLN_TGMainFrame;
extern G__linked_taginfo G__MyMainFrameDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__MyMainFrameDictLN_TGNumberEntry;
extern G__linked_taginfo G__MyMainFrameDictLN_TGLabel;
extern G__linked_taginfo G__MyMainFrameDictLN_TGHProgressBar;
extern G__linked_taginfo G__MyMainFrameDictLN_MyMainFrame;

/* STUB derived class for protected member access */
